[".mozilla/firefox/profiles/{{ .firefox.profile_name }}/extensions/uBlock0@raymondhill.net.xpi"]
type = "file"
url = "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi"
refreshPeriod = "168h"

[".mozilla/firefox/profiles/{{ .firefox.profile_name }}/extensions/{446900e4-71c2-419f-a6a7-df9c091e268b}.xpi"]
type = "file"
url = "https://addons.mozilla.org/firefox/downloads/latest/bitwarden-password-manager/latest.xpi"
refreshPeriod = "168h"

[".mozilla/firefox/profiles/{{ .firefox.profile_name }}/extensions/magnolia@12.34.xpi"]
type = "file"
url = "https://gitflic.ru/project/magnolia1234/bpc_uploads/blob/raw?file=bypass_paywalls_clean-latest.xpi"
refreshPeriod = "168h"

[".mozilla/firefox/profiles/{{ .firefox.profile_name }}/extensions/addon@darkreader.org.xpi"]
type = "file"
url = "https://addons.mozilla.org/firefox/downloads/latest/darkreader/latest.xpi"
refreshPeriod = "168h"

[".mozilla/firefox/profiles/{{ .firefox.profile_name }}/extensions/{762f9885-5a13-4abd-9c77-433dcd38b8fd}.xpi"]
type = "file"
url = "https://addons.mozilla.org/firefox/downloads/latest/return-youtube-dislikes/latest.xpi"
refreshPeriod = "168h"

[".mozilla/firefox/profiles/{{ .firefox.profile_name }}/extensions/sponsorBlocker@ajay.app.xpi"]
type = "file"
url = "https://addons.mozilla.org/firefox/downloads/latest/sponsorblock/latest.xpi"
refreshPeriod = "168h"

[".mozilla/firefox/profiles/{{ .firefox.profile_name }}/extensions/{f209234a-76f0-4735-9920-eb62507a54cd}.xpi"]
type = "file"
url = "https://addons.mozilla.org/firefox/downloads/latest/unpaywall/latest.xpi"
refreshPeriod = "168h"

[".mozilla/firefox/profiles/{{ .firefox.profile_name }}/extensions/harper@writewithharper.com.xpi"]
type = "file"
url = "https://addons.mozilla.org/firefox/downloads/latest/private-grammar-checker-harper/latest.xpi"
refreshPeriod = "168h"

[".mozilla/firefox/profiles/{{ .firefox.profile_name }}/extensions/{3579f63b-d8ee-424f-bbb6-6d0ce3285e6a}.xpi"]
type = "file"
url = "https://addons.mozilla.org/firefox/downloads/latest/chameleon-ext/latest.xpi"
refreshPeriod = "168h"

[".mozilla/firefox/profiles/{{ .firefox.profile_name }}/extensions/adguard-extra-beta@adguard.com.xpi"]
type = "file"
url = "https://agrd.io/adguard_extra_firefox_beta"
refreshPeriod = "168h"
