[".local/bin/oh-my-posh"]
type = "file"
url = "https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
executable = true
refreshPeriod = "168h"
