["{{ .paths.zsh_plugins }}/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting"
refreshPeriod = "168h"

["{{ .paths.zsh_plugins }}/git-open"]
type = "git-repo"
url = "https://github.com/paulirish/git-open"
refreshPeriod = "168h"

["{{ .paths.zsh_plugins }}/zsh-nvm"]
type = "git-repo"
url = "https://github.com/lukechilds/zsh-nvm"
refreshPeriod = "168h"

["{{ .paths.zsh_plugins }}/zsh-completions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-completions"
refreshPeriod = "168h"

["{{ .paths.zsh_plugins }}/tmux"]
type = "archive"
url = "https://github.com/ohmyzsh/ohmyzsh/archive/refs/heads/master.tar.gz"
stripComponents = 3
include = ["ohmyzsh-master/plugins/tmux/**"]
refreshPeriod = "168h"
