#!/usr/bin/env bash

pgrep -x systemd-udevd >/dev/null 2>&1 || pgrep -x udevd >/dev/null 2>&1 || {
  echo "Error: udev is not running. Does this system use udev?"
  exit 1
}

DEVICES=$(lsusb | nl -s ". ")
printf "%s\n" "$DEVICES"

read -p "Select a device: " device

SELECTION=$(echo "$DEVICES" | awk "NR==$device")

ID=$(grep -oP 'ID \K[0-9a-fA-F]{4}:[0-9a-fA-F]{4}' <<<"$SELECTION")
VENDOR_ID=${ID%:*}
PRODUCT_ID=${ID#*:}

if [ -z "$VENDOR_ID" ] || [ -z "$PRODUCT_ID" ]; then
  echo "Could not find device IDs"
  exit 1
fi

read -p "Enter rule name: " rule_name

RULE="KERNEL==\"hidraw*\", ATTRS{idVendor}==\"$VENDOR_ID\", ATTRS{idProduct}==\"$PRODUCT_ID\", TAG+=\"uaccess\""

echo "$RULE" | sudo tee "/etc/udev/rules.d/99-$rule_name.rules"

sudo udevadm control --reload-rules
sudo udevadm trigger
