#!/usr/bin/env bash

# export SSH_AUTH_SOCK="$HOME/.bitwarden-ssh-agent.sock"
auth_sock_paths=(
  "$HOME/.bitwarden-ssh-agent.sock"
  "$HOME/.var/app/com.bitwarden.desktop/data/.bitwarden-ssh-agent.sock"
  "$HOME/snap/bitwarden/current/.bitwarden-ssh-agent.sock"
)

auth_sock_path=""
for path in "${auth_sock_paths[@]}"; do
  if [[ -e "$path" ]]; then
    auth_sock_path=$path
    break
  fi
done

if [[ -z "$auth_sock_path" ]]; then
  echo "Could not find Bitwarden SSH Agent socket"
  exit 1
fi

echo "Found Bitwarden SSH Agent socket at $auth_sock_path"
