import = ["~/.config/alacritty/themes/themes/dark_plus.toml"]

[shell]
program = "/bin/zsh"

[window]
dimensions = { columns = 100, lines =  35 }
padding.x = 10
padding.y = 10

[font]
size = 15
normal.family = "JetBrainsMonoNL Nerd Font"
normal.style = "Regular"
bold.style = "Bold"
italic.style = "Italic"
bold_italic.style = "Bold Italic"

