import = [
    "~/.config/alacritty/themes/themes/dark_plus.toml"
]

[env]
TERM = "alacritty"

[window]
dimensions = { columns = 90, lines =  29 }
padding.x = 10
padding.y = 10

[font]
size = 15

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"


